"""Write conservative stub editorials for 10 round-3 facilities the agents
left empty (over-cautious 'thin' classifications). Tone-neutral framing."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SPREADSHEET_ID = '1HpAXH9aG1O27Cvhfu4MIOa9sRYhwIL4C_WUoFfC-9qk'
TOKEN_FILE = 'token_sheets.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
TAB = 'google-sheets-facilities.csv'

STUBS = [
    (282, 'pusat-jagaan-warga-emas-suria',
     "Pusat Jagaan Warga Emas Suria is listed as a nursing home in Seksyen 7, Shah Alam — a mature residential township with reasonable access to major Shah Alam clinics and the broader Klang Valley hospital network. The home is contactable on +60 3-7958 5055.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. Bed count, staffing model, the scope of medical care, religious or cultural orientation, and JKM registration are best confirmed on a call. Seksyen 7 is a mixed residential-commercial neighbourhood that supports a number of small community-scale homes.\n\nFamilies considering this centre should call ahead to establish whether it is currently taking residents and what level of care is offered. Useful questions: how many beds, registered-nurse cover overnight, doctor-visit frequency, the dependency levels accepted (ambulant, partial-care, bedridden), the current monthly fee, and the JKM licence number. A short visit will give a clearer picture of day-to-day conditions than the listing alone."),

    (225, 'city-home-care-centre',
     "City Home Care Centre is listed as a nursing home in Taman Chi Liung, Klang — a township in the Klang corridor with reasonable proximity to Hospital Tengku Ampuan Rahimah (HTAR), the main public hospital for the Klang area. The home is contactable on +60 16-612 3368.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. Bed count, staffing model, care scope, and JKM registration status are best confirmed on a call or in person. Taman Chi Liung is a residential neighbourhood that supports several smaller community homes operating from converted terrace or shop premises.\n\nFamilies considering this centre should call ahead to establish whether it is currently taking residents and what care types are available. Useful questions: registered-nurse cover, doctor-visit frequency, dependency levels accepted (ambulant, partial-care, bedridden), monthly fees, JKM licence number, and the protocol for medical escalations to HTAR. A short visit during a meal or activity time is the most reliable way to get a feel for the home."),

    (293, 'pusat-jagaan-warga-emas-kaseh-bonda',
     "Pusat Jagaan Warga Emas Kaseh Bonda is listed in Bandar Country Homes, Rawang — an outer northern Selangor township. The Google listing categorises it as a home health care service and lodging facility, which suggests it may operate as a smaller residential home rather than a fully clinical nursing home, though this is best confirmed directly. The home is contactable on +60 11-1111 7844.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered on a call. The 'home health care' classification can imply visiting nursing services, residential lodging, or both — clarifying which mode applies will help families understand if Kaseh Bonda matches their needs. The Bandar Country Homes location is on the outer edge of the Klang Valley, with the nearest major hospital being Hospital Selayang.\n\nFamilies considering this home should call ahead to establish current operating hours, what care types are offered, and whether it accepts residential placements or only home-care visits. Useful questions: registered-nurse availability, dependency levels accepted, monthly fees, JKM licence status, and the protocol for medical escalations from the Rawang area."),

    (307, 'emerald-nursing-care-home-usj-subang-jaya-elderly-home-梳邦再也疗养院',
     "Emerald Nursing Care Home (USJ & Subang Jaya Elderly Home, 梳邦再也疗养院) is listed in Putra Heights — a planned township in southern Subang Jaya served by the LRT and within reasonable distance of Sunway Medical Centre and Subang Jaya Medical Centre. The Google listing categorises it as a nursing home, rehabilitation centre, and wellness centre, suggesting a broader rehabilitation-and-recovery focus alongside residential care. The home is contactable on +60 18-987 3862.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. The Mandarin name (梳邦再也疗养院) suggests the home likely serves the local Chinese community in Putra Heights and surrounding USJ neighbourhoods. Care scope, bed count, staffing, and JKM registration are best confirmed on a call.\n\nFamilies considering this home should call ahead to establish current admission availability and what rehabilitation programmes are run on-site. Useful questions: physiotherapy and occupational-therapy capability, registered-nurse cover, doctor-visit frequency, languages used by staff, dependency levels accepted, monthly fees, and the JKM licence number. The Putra Heights location is a practical asset for families anticipating hospital escalations."),

    (188, 'canaan-home',
     "Canaan Home is listed as a retirement home in Kampung Indah Permai — a residential pocket in the broader Ampang corridor of Selangor. The name 'Canaan' (迦南) carries a Christian connotation, suggesting the home may serve, or have been founded by, a Christian community in the area. The home is contactable on +60 14-682 8622.\n\nThe home keeps a low online profile, with a Facebook page that is not publicly browsable and no published website, so most service detail is best gathered on a call. The 'retirement home' classification typically implies a focus on independent or low-dependency seniors rather than high-acuity nursing cases, but this is best confirmed directly. Kampung Indah Permai is a neighbourhood-scale residential setting, consistent with smaller community homes in the area.\n\nFamilies considering Canaan Home should call ahead to establish current admission criteria, religious or cultural orientation, and what dependency levels the home accepts. Useful questions: bed count, registered-nurse availability, daily routines and activities, dietary arrangements, monthly fees, and the JKM licence status. A short visit will give the clearest sense of the home's character and whether it suits a particular resident."),

    (190, 'blissful-family-old-folks-nursing-home',
     "Blissful Family Old Folks Nursing Home is listed in Taman Bukit Indah — a residential township in the southern Klang Valley. The Google listing categorises it under aged care. The home is contactable on +60 16-323 7258.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. Bed count, staffing model, the scope of medical care, and JKM registration are best confirmed on a call. The Taman Bukit Indah area is a mixed residential neighbourhood that supports several smaller community-scale aged-care providers.\n\nFamilies considering this home should call ahead to establish current operating status, what care types are offered, and the scale of the operation. Useful questions: bed count, registered-nurse cover overnight, doctor-visit frequency, dependency levels accepted, monthly fees, and the JKM licence number. Smaller community homes are often best understood through a short visit, where the staff-to-resident dynamic and physical environment are visible in a way listings cannot convey."),

    (223, 'aurora-home-care-centre',
     "Aurora Home Care Centre is listed as a nursing agency in Kawasan 17, Klang — a mixed industrial-residential area in central Klang. A nursing-agency classification typically implies the centre dispatches registered nurses or trained caregivers to clients' homes rather than (or alongside) operating residential beds. The home is contactable on +60 16-690 6333.\n\nThe centre keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. Whether Aurora is primarily a home-care dispatch service, a residential facility, or both is best confirmed on a call. Home-care agencies in Malaysia commonly cover post-discharge nursing, wound care, dementia support, and live-in caregiving by the day or month.\n\nFamilies considering Aurora should call ahead to establish whether they need a residential bed or a home-deployed caregiver, and what each option costs. Useful questions: the LJM (Lembaga Jururawat Malaysia) registration of nurses on the roster, the daily and monthly rates for stay-in versus shift work, the back-up arrangement when an assigned caregiver falls ill, and the supervising nurse's contact details. Confirming a clear care plan in writing is sensible before engaging any home-care service."),

    (243, 'pusat-jagaan-warga-emas-penyayang',
     "Pusat Jagaan Warga Emas Penyayang is listed in Taman Serdang Raya, Seri Kembangan — a well-connected township southeast of Kuala Lumpur with reasonable access to Columbia Asia Hospital Cheras and several private medical clinics. The Google listing categorises it under aged care. The home is contactable on +60 12-203 9932.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. Bed count, staffing, the scope of medical care, and JKM registration are best confirmed on a call. Taman Serdang Raya is a mature residential township with multiple smaller community-scale care homes catering to local families.\n\nFamilies considering this centre should call ahead to establish current admission availability and the level of care offered. Useful questions: bed count, registered-nurse cover, doctor-visit frequency, dependency levels accepted (ambulant, partial-care, bedridden), monthly fees, and the JKM licence number. The Serdang location is a practical asset for families anticipating hospital escalations to UPM Teaching Hospital or Columbia Asia."),

    (365, 'bethel-retirement-home-plt',
     "Bethel Retirement Home PLT is listed in Kawasan 6, Shah Alam, registered as a Limited Liability Partnership (PLT). The 'Bethel' name carries a Christian connotation, which often signals a faith-aligned operating ethos, though this is best confirmed directly. The home is contactable on 03-3381 6742.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered on a call. Bed count, the scope of medical care, religious orientation, and JKM registration are best confirmed directly with the operator. Kawasan 6 is a mixed residential-industrial neighbourhood in central Shah Alam, supporting a number of smaller community-scale care homes.\n\nFamilies considering Bethel should call ahead to establish current admission availability and what level of care the home is set up to deliver. Useful questions: bed count, registered-nurse cover, doctor-visit frequency, dependency levels accepted, religious or dietary considerations, monthly fees, and the JKM licence number. A short visit during a meal or activity time will give a clearer sense of the home's daily rhythm and whether it suits a particular resident."),

    (292, 'pusat-jagaan-warga-emas-semenyih',
     "Pusat Jagaan Warga Emas Semenyih is listed in Bandar Teknologi Kajang — a township on the southern edge of the Klang Valley near Semenyih and Broga. The Google listing categorises it as a social welfare centre, which typically implies a charity or donation-funded operating model rather than a fully commercial nursing home. The home is contactable on +60 10-253 6750.\n\nThe home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered directly. As a welfare-oriented home, admission may be means-tested or referral-based via JKM caseworkers rather than a private admission process. Bed count, staffing, and the scope of medical care are best confirmed on a call.\n\nFamilies interested in welfare-oriented homes are usually best served by contacting JKM Selangor first to clarify eligibility and the referral pathway. Useful questions when calling the home directly: current admission availability, registered-nurse or caregiver coverage, dependency levels accepted, donation or fee arrangements, and the JKM licence number. JKM caseworkers can also point families to other suitable welfare homes in the Kajang/Semenyih area if Penyayang Semenyih is full."),
]

def main():
    creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    sheet = build('sheets', 'v4', credentials=creds).spreadsheets()
    data = []
    for row, slug, ed in STUBS:
        data.append({'range': f"'{TAB}'!AY{row}", 'values': [[ed]]})
        print(f'  AY{row}  {slug[:55]:55s}  ({len(ed.split())}w)')
    body = {'valueInputOption': 'RAW', 'data': data}
    resp = sheet.values().batchUpdate(spreadsheetId=SPREADSHEET_ID, body=body).execute()
    print(f"\nUpdated {resp.get('totalUpdatedCells')} cells.")

if __name__ == '__main__':
    main()
