"""Fix 11 round-3 editorials with critical/undermining tone. Upload corrected versions."""
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

SPREADSHEET_ID = '1HpAXH9aG1O27Cvhfu4MIOa9sRYhwIL4C_WUoFfC-9qk'
TOKEN_FILE = 'token_sheets.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets']
TAB = 'google-sheets-facilities.csv'

FIXES = [
    (253, 'pusat-jagaan-warga-tua-sra',
     "Pusat Jagaan Warga Tua SRA was founded on 1 January 2020 by Sharil Hussein, a former Ministry of Health civil servant, as a protective shelter for elderly people discharged or abandoned from hospitals whose families cannot provide care. The home is located in Taman Malawati, Kuala Selangor — a suburban setting roughly an hour from central Kuala Lumpur. Residents are drawn predominantly from referrals through the hospital system rather than private placements, reflecting the founder's healthcare background and the NGO's welfare-first mandate. The facility is operated under the Selangor Relief Agency (SRA) umbrella.\n\nAs of early 2025, the home was caring for 34 elderly and frail residents. Funding has historically come from Selangor Zakat Board support, and the home has periodically run public appeals for donations to maintain its rented bungalow. Local welfare partners (including Mayda) have stepped in at various points to support premises and operating costs. The resident profile appears to include bedridden and uzur (severely debilitated) individuals, suggesting the home handles higher-dependency cases beyond basic assisted living.\n\nThe home runs a welfare-first model, so families considering a placement here should call ahead on +60 19-879 1926 to confirm current admission criteria, the latest fee structure for non-asnaf residents, and the current operating premises. Useful questions: the care team composition, whether nursing staff are available overnight, and how the home manages medical escalations given the Kuala Selangor location. SRA also welcomes volunteer and donor enquiries through the same number."),

    (299, 'pusat-jagaan-warga-tua-impresif',
     "Pusat Jagaan Warga Tua Impresif sits in a residential pocket of PJS 7, Petaling Jaya, at Jalan Bukit Menteri Selatan 7/2. It is classified as a non-profit organisation on Google, which suggests it may operate on a welfare or charitable footing rather than as a fully commercial nursing home — though this has not been independently confirmed. The location gives reasonable access to the Asia Jaya area and several bus routes serving the PJ Selatan corridor.\n\nThe home keeps a low online profile — no website or Facebook page — and is best contacted directly via the listed phone number (03-7954 9008). Bed count, staffing, the scope of medical care provided, and JKM registration status are best confirmed on a call. The non-profit classification could mean it operates as a charity home with subsidised placements, or it could reflect an outdated business-type tag on the listing.\n\nFamilies considering this centre should call first to establish whether it is taking new residents, what level of care is provided, and whether there is a waiting list as is common with welfare-based homes. Useful questions when calling: the JKM licensing status, whether a registered nurse is on staff, and whether the home accepts bedridden residents. A short visit will give a much clearer picture than the listing alone."),

    (169, 'utopia-care-center',
     "Utopia Care Center is listed at an address in Taman Makmur, a residential area in the Ampang district of Selangor, accessible via the Ampang corridor with links to public hospitals serving the east Klang Valley. The Google listing categorises it as a nursing home and shows a contact of 011-3323 0611 with a 5-star rating from a small but consistently positive group of reviewers.\n\nThe home keeps a low online profile — no published website, Facebook page, or third-party directory entry was found during research — so most service detail is best gathered directly. Bed count, staffing levels, care scope, pricing, language of operations, and JKM registration are best confirmed with the operator on a call. The Taman Makmur area is predominantly residential, and many smaller care homes in such settings operate from converted terrace houses with a limited bed count.\n\nFamilies should call 011-3323 0611 to establish whether the home is currently taking residents and what care level is available. Useful questions: how many beds are there, is there a registered nurse on site, can they handle bedridden or post-stroke residents, what is the monthly cost, and what is the current JKM licence number. A site visit before placement is the most reliable way to assess fit, especially for smaller community-style homes."),

    (277, 'elderly-care-centre',
     "Elderly Care Centre is listed under a Subang Jaya address in the SS14 area with a phone number (+60 18-383 7704). The Google listing carries three 4.7-star reviews and an SS14 pin. The home keeps a low online profile and does not maintain a published website or active social media page, so most service detail is best gathered on a call or visit. SS14 is a mature residential neighbourhood in Subang Jaya with reasonable proximity to Subang Jaya Medical Centre.\n\nBed count, staffing, care scope, and JKM registration status are best confirmed directly with the home. Smaller community homes in established Subang Jaya neighbourhoods often operate quietly through word-of-mouth referrals rather than digital marketing, so the limited online footprint is not unusual. The SUMC proximity is a practical asset for families who anticipate needing hospital escalations.\n\nFamilies considering this centre should call first to establish what care types are offered, whether it holds a current JKM licence, how many residents it accommodates, the nursing staff qualifications, and what medical complexity it can handle. A site visit during a mealtime or activity period is the most reliable way to assess day-to-day conditions before making a placement decision."),

    (181, 'kajang-nursing-home',
     "Kajang Nursing Home appears at 142 Jalan Bukit in Kajang town proper — a central Kajang address that gives it reasonable proximity to Hospital Kajang (under 3 km) and KPJ Kajang Specialist Hospital. A landline number (+60 3-6737 3571) is the listed contact. The home does not maintain a published website or active social media page, so most service detail is best gathered on a call or visit. The Google Maps entry carries three reviews.\n\nThe name 'Kajang Nursing Home' implies a nursing-level rather than purely social-care operation. Staffing model, capacity, clinical capability, and operating history are best confirmed directly with the home. The central Kajang Jaya township location in a residential area is typical of smaller, community-embedded homes that may serve long-term Kajang residents who prefer staying local.\n\nFamilies considering this home should call ahead to establish whether it is currently accepting residents, confirm licence status with JKM Selangor, ask about nursing coverage overnight, and visit in person before committing. Useful questions when calling: the JKM licence number, registered-nurse coverage on each shift, doctor-visit frequency, and current monthly fees. A short visit will give a clearer picture of day-to-day conditions than the listing alone."),

    (241, 'athena-care-centre-klang',
     "Athena Care Centre is pinned to Taman Sri Andalas, a township in the southern Klang area with reasonable proximity to Hospital Tengku Ampuan Rahimah — the main public hospital for Klang — roughly 8–10 km away. The home is contactable via the Google Maps listing and carries 5-star reviews from a small reviewer base. The home does not maintain a published website or Facebook page, so most service detail is best gathered on a call or visit.\n\nCare types offered, JKM licence number, capacity, and on-duty nursing capability are best confirmed directly with the home. Taman Sri Andalas is a mixed residential-commercial area that supports a number of small community nursing homes, often operating from converted terrace or shop premises. The proximity to HTAR is a practical asset for families anticipating hospital escalations.\n\nFamilies should call the listed number to confirm the home is currently accepting residents, establish care type and licence status, and arrange a site visit before considering placement. Useful questions on the call: the JKM licence number, the registered-nurse cover overnight, the visiting-doctor frequency, the monthly fee, and what the protocol is for medical emergencies."),

    (289, 'pusat-penjagaan-warga-emas-hati-mesra',
     "Pusat Penjagaan Warga Emas Hati Mesra appears in Taman Nirwana, which falls within the broader Ampang corridor in Selangor — an area with access to Ampang Puteri Specialist Hospital and Hospital Ampang. The centre is categorised as a charity operation, consistent with donation-funded Islamic welfare homes (rumah kebajikan) that typically serve lower-income elderly residents who may have limited family support. The home carries two 5-star Google reviews.\n\nThe home keeps a very low online profile and is not currently reachable through a publicly listed phone number or website — most welfare homes in this category operate via JKM social-welfare referrals rather than direct private enquiries. A 'charity' care type in the Malaysian context typically implies means-tested admission, donor-funded operations, and care provided largely by volunteers or welfare officers, though some charity homes do employ qualified nursing staff.\n\nFamilies interested in this type of welfare-oriented home are usually best served by contacting JKM Selangor directly to confirm the centre's registration, eligibility criteria, and current operational status. Placement in a charity home usually requires a social-welfare referral rather than a private admission process, and capacity is often limited. JKM caseworkers can also point families to other suitable welfare homes in the Ampang area if Hati Mesra is full."),

    (170, 'sunshine-nursing-home-care',
     "Sunshine Nursing Home Care is listed in Bukit Sentosa, an outer residential area in the Rawang district of northern Selangor. The centre maintains a Facebook presence with limited content and is best contacted directly. A pricing reference of RM50 per day (approximately RM1,500/month) including diapers and 24-hour care has appeared in directory listings attributed to their Facebook page, which would position it at the budget end of the market. This figure is best confirmed directly as it may reflect an older rate or a basic shared-room package.\n\nThe Bukit Sentosa location is on the outer edge of the Klang Valley — the nearest major hospitals are Hospital Selayang and facilities in Sungai Buloh, so families should account for travel time when planning escalations. For medically stable, low-dependency elderly residents whose families live in the Rawang-Bukit Sentosa corridor, the proximity can be an advantage in terms of family visiting frequency. The home carries a small number of Google reviews.\n\nFamilies should call the listed number (+60 12-474 6615), visit in person, and ask about nursing-staff qualifications and overnight coverage. At budget pricing, the model often leans on trained caregivers rather than registered nurses, which may be a fit for ambulant or minimally dependent residents. Useful questions on the call: the JKM licence number, registered-nurse cover, doctor-visit frequency, medication and tube-feeding capability, and the protocol for hospital transfers."),

    (399, 'pusat-jagaan-jivi',
     "Pusat Jagaan Jivi is a small residential care centre in Section 11, Petaling Jaya, reachable on +603-7931 9497, with additional contact persons listed as Ms Lucy and Mdm Avayee — Tamil-sounding names that suggest the facility likely serves, or was founded to serve, the Indian community in the Petaling Jaya area. Section 11 is a mature mixed-residential neighbourhood with easy access to public transport, and the centre operates at a reported capacity of 15 beds. The home keeps a low online profile, with a minimal Facebook presence and a single Google rating on record.\n\nThe care type is not publicly published, so the level of nursing care versus basic custodial support is best confirmed directly with the home. The 15-bed size is consistent with a small family-run or community-run home. The Tamil connection, if accurate, may mean Jivi serves seniors who are more comfortable in Tamil or other South Indian languages, which can be a significant advantage for Indian families in PJ who want a culturally familiar placement.\n\nFamilies considering Jivi should treat this as an early-stage enquiry: confirm JKM registration status, ask what medical oversight is in place (whether a doctor or nurse visits regularly), and clarify what care dependency levels the home can manage. A short physical visit is the most reliable way to assess whether it suits a particular resident's needs, especially for smaller community homes where the right cultural and linguistic fit matters."),

    (247, 'pusat-jagaan-persatuan-kebajikan-warga-emas-chan-kl',
     "Pusat Jagaan Persatuan Kebajikan Warga Emas Chan KL — also known informally as 安安老人院 (An An Old Folks Home) — is a welfare-oriented elderly care centre in the Pandan Indah / Ampang Jaya area of Selangor, operated by a Chinese community welfare association bearing the Chan family name. The Malay listing includes 'KL' in its title despite being situated in Selangor, reflecting its proximity to the Ampang border with Kuala Lumpur. It maintains a Facebook presence (pusatjagaanwargaemaschan) and is navigable via Waze. The Google listing categorises it as a 'social services organisation' rather than a formal nursing home — a meaningful distinction for families looking for nursing-grade care.\n\nAs a welfare association home, An An is likely structured around community charity rather than commercial care delivery — meaning it may accept subsidised or low-income referrals alongside self-paying residents. The 'languages: 30' data point in the source file appears to be a data entry error rather than a languages field. Bed count, the care dependency levels managed, and JKM registration status are best confirmed directly with the home.\n\nFamilies should clarify upfront whether the home is JKM-registered as a residential care facility, what nursing qualifications staff hold, and what happens when a resident's medical needs escalate beyond what the home can manage. If it is primarily a social-welfare placement rather than a nursing home, it may not be suited to residents who need wound care, PEG feeding, or dementia-specific programmes. A short visit in person is the most reliable way to assess the physical environment and staffing model."),

    (375, 'pusat-jagaan-orang-tua-apex-way',
     "Pusat Jagaan Orang Tua Apex Way is a private residential elderly care home (registered category: W/T Berkediaman Swasta) at Jalan LP 4/5, Taman Lestari Perdana, Seri Kembangan — a well-connected suburb southeast of Kuala Lumpur. The facility can be reached on 03-89429993 and is listed with a reported capacity of 30 beds. It sits in a neighbourhood served by multiple bus routes (540, T543, T545, 541, SJ05) and is within the MRT network's catchment, making it reasonably accessible for visiting family members without a car.\n\nThe home keeps a low online profile, with no published website or Facebook page, so most service detail is best gathered on a call or visit. As a registered private residential home in the Seri Kembangan corridor, Apex Way is positioned to provide basic to moderate-dependency residential care. Specific clinical capabilities — registered-nurse coverage, doctor-visit frequency, wound-care, and dementia capacity — are best confirmed directly with the home.\n\nFamilies should use an initial phone call to establish the current JKM operating-licence number, the level of medical supervision on-site, and how the home handles residents who develop higher-acuity needs over time. The Seri Kembangan location places it reasonably close to Columbia Asia Hospital Cheras and several GP clinics, which is a practical asset if emergencies arise. A site visit before committing is advisable for any smaller community-scale home."),
]

def main():
    creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    sheet = build('sheets', 'v4', credentials=creds).spreadsheets()
    data = []
    for row, slug, ed in FIXES:
        data.append({'range': f"'{TAB}'!AY{row}", 'values': [[ed]]})
        try:
            print(f'  AY{row}  {slug[:55]:55s}  ({len(ed.split())}w)')
        except UnicodeEncodeError:
            print(f'  AY{row}  <unicode>  ({len(ed.split())}w)')
    body = {'valueInputOption': 'RAW', 'data': data}
    resp = sheet.values().batchUpdate(spreadsheetId=SPREADSHEET_ID, body=body).execute()
    print(f"\nUpdated {resp.get('totalUpdatedCells')} cells.")

if __name__ == '__main__':
    main()
